### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by 22u2** [pierre3/PlantUmlClassDiagramGenerator#1]
Great work, I was about to start a project like that!

It would be great if we can see the base classes, created with "<|--"

**Comment by pierre3** [comment]
Thank you for your feedback. 
I'll think about the output of inheritance relationships.

**Comment by pierre3** [comment]
I tried to output the inheritance relationships between a subclass and a baseclass.
Please check [this commit](https://github.com/pierre3/PlantUmlClassDiagramGenerator/commit/2ade528976d407d10bf48c2902f1e4d09aa89439
).
```cs
class ClassB : ClassA{
}
```

```
class ClassB : ClassA {
}
ClassA <|-- ClassB
```

**Comment by 22u2** [comment]
It works fine, thx

**Comment by pierre3** [comment]
closed
