### ISSUE TITLE
Casing typo

### ISSUE THREAD

**Issue by thild** [pierre3/PlantUmlClassDiagramGenerator#15]
`.vscode/extensions/pierre3.csharp-to-plantuml-1.0.0/lib/PlantumlClassDiagramGenerator/PlantUmlClassDiagramGenerator.dll` not found on Linux.

There is a casing typo in PlantumlClassDiagramGenerator.

https://github.com/pierre3/PlantUmlClassDiagramGenerator/blob/df44b33168f979c7de9ba4510a35b8a8761eb8e4/tools/csharp-to-plantuml/src/extension.ts#L30

**Comment by pierre3** [comment]
I merged.
Thank you for fixing it. 
Please check the new release v1.2.0.
