### ISSUE TITLE
All-in-one diagram

### ISSUE THREAD

**Issue by marsop** [pierre3/PlantUmlClassDiagramGenerator#19]
At the moment, when generating a diagram including several classes, each .cs file will be mapped to a .puml file and then an "include.puml" file will be created adding them all. This is all good and fine as long as you are not working with ServerRendering, in which case there is no way to see a diagram integrating all diagrams at once. Is there any plans to add an option in order to create a new "all-included" file?

**Comment by pierre3** [comment]
I merged your PR.
Thank you for the feature!
Please check [new release v1.2.0](https://www.nuget.org/packages/PlantUmlClassDiagramGenerator/1.2.0)
