### ISSUE TITLE
In VSCode, output path is relative to input path, not workspace folder

### ISSUE THREAD

**Issue by stanwest** [pierre3/PlantUmlClassDiagramGenerator#26]
Thank you for the extension to Visual Studio Code.

The description of the `csharp2plantuml.outputPath` configuration option states that its value is relative to the workspace folder. However, the actual behavior (from [this line](https://github.com/pierre3/PlantUmlClassDiagramGenerator/blob/2d698845af3140626bb970cb4a535da6895b251d/tools/csharp-to-plantuml/src/extension.ts#L42)) is that the output folder option is relative to the input folder. Please consider resolving the conflict in favor of the documentation, such that the value is relative to the workspace folder.

**Comment by Vivraan** [comment]
Fixing this in a PR.

**Comment by Vivraan** [comment]
Meanwhile, in your `extension.js`, change this:
```js
if (outputPath !== "") {
            command += ` "${path_1.join(input, outputPath)}"`;
        }
```

to this:
```js
if (outputPath !== "") {
            command += ` "${path_1.join(wsroot, outputPath)}"`;
        }
```

**Comment by pierre3** [comment]
@Vivraan 
Merged. Thank you for your PR!
