### ISSUE TITLE
Typo in a setting name

### ISSUE THREAD

**Issue by mikeazurek** [pierre3/PlantUmlClassDiagramGenerator#29]
![image](https://user-images.githubusercontent.com/58667581/90983996-7890a800-e572-11ea-87e4-8816db420faf.png)
I guess "cshap2plantuml.allInOne" should be "csharp2plantuml.allInOne"

**Comment by Vivraan** [comment]
Making a PR for this.

**Comment by Vivraan** [comment]
Damn, it looks like that line was added in the last minute to the market extension, it isn't there in the source.

**Comment by Vivraan** [comment]
For now, fix that typo in `{Your Drive}:\Users\{YouUser}\.vscode\package.json` (are you on Windows?).

**Comment by pierre3** [comment]
@Vivraan 
Merged. Thank you for your PR!
