### ISSUE TITLE
Generated include.puml is wrong when using ". -dir"

### ISSUE THREAD

**Issue by msallin** [pierre3/PlantUmlClassDiagramGenerator#4]
The references in the include.puml are wrong when using "." to point to the current directory.
E.g. it produces

`!include .\\Sample\Program.\puml`

but it should be

`!include .\\SwemSample\Program\puml`

**Comment by msallin** [comment]
PR created.

**Comment by pierre3** [comment]
Thank you for your feedback!
I Merged, and released v 1.0.0.2.

https://www.nuget.org/packages/PlantUmlClassDiagramGenerator/1.0.0.2
