### ISSUE TITLE
[Feature Request] Support for record types

### ISSUE THREAD

**Issue by haakobja** [pierre3/PlantUmlClassDiagramGenerator#42]
Hi,
I recently tried to incorporate this dotnet tool in my project where I use and target dotnet 5. It seems like the tool doesn't handle records correctly. Whenever I use a record in my source, the output results in an invalid plantuml file.

Consider the following. I've got the following record
```csharp
    public record ExampleRecord {
      public int AnInt { get; }
      public string AStringValue { get; }
    }
```

When I pass this through the generator, I get the following PlantUml spec:
```plantuml
+ AnInt : int <<get>>
+ AStringValue : string <<get>>
```

I would expect record to be handled the same way as classes, at least in the beginning. And by the way the following record notation doesn't output anything at all, which is expected as it's a new notation type that is record specific.

```csharp
public record ExampleRecord (int AnInt, string AStringValue);
```

**Comment by DrPepperBianco** [comment]
I added support for records and created a pull request.

**Comment by PendingChanges** [comment]
Can be closed as records are now supported
