### ISSUE TITLE
update for dotnet 6 ?

### ISSUE THREAD

**Issue by bklaase** [pierre3/PlantUmlClassDiagramGenerator#50]
Would it be possible to update this one to support dotnet 6?

**Comment by jeroenhabets** [comment]
I would be interested in dotnet 6 support as well.

**Comment by chraxo** [comment]
I added a pull request for updating to dotnet 6 (see #53)

**Comment by jeroenhabets** [comment]
FYI: TargetFramework `net6.0` was already released as part of 1.2.5 (https://www.nuget.org/packages/PlantUmlClassDiagramGenerator/1.2.5#releasenotes-body-tab)
