### ISSUE TITLE
Do we have build which will be suitable for 6.0.3?

### ISSUE THREAD

**Issue by seesiva** [pierre3/PlantUmlClassDiagramGenerator#52]
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.3 at [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=5.0.0&arch=x64&rid=win10-x64

**Comment by seesiva** [comment]
Duplicate of #50

**Comment by jeroenhabets** [comment]
> Duplicate of https://github.com/pierre3/PlantUmlClassDiagramGenerator/issues/50

@seesiva correct so please close this one (https://github.com/pierre3/PlantUmlClassDiagramGenerator/issues/52)
