### ISSUE TITLE
excludePaths should allow excluding paths on all folder levels

### ISSUE THREAD

**Issue by chraxo** [pierre3/PlantUmlClassDiagramGenerator#66]
## Current situation

Currently the excludePaths argument filters only the exact specified path and does not allow filtering for all folders on all subfolder levels.

Example: 

    C:\dev\my-app> puml-gen -excludePaths obj 

This call excludes `C:\dev\my-app\obj`, but it does *not* exclude for example `C:\dev\my-app\projectAbc\obj`. 

When using PlantUmlClassDiagramGenerator with a solution that contains multiple projects, this leads to a quite long list of excludePaths. Also, when new projects are added, or an existing project is renamed, then each time the excludePaths have to be adapted.

## Proposal

It should be possible to generically filter all folders with a specific name, independent of the subfolder level where it is located.

Therefore wildcard characters should be allowed, such as known from `.gitignore`. For example to skip all `obj` folders on all levels the following parameter could be used:

    puml-gen -excludePaths **/obj

Benefits:
* Increases the flexibility.
* The pattern is widely known.
* No breaking api change.
* The change is relatively easy to implement.

I would be happy to provide the implementation, if you agree with such a change.

**Comment by hugh-maaskant** [comment]
I have the same issue, so please consider this an up-vote :-)
