### ISSUE TITLE
Plugin for VS Code

### ISSUE THREAD

**Issue by hellboy81** [pierre3/PlantUmlClassDiagramGenerator#7]
subj

**Comment by InRedikaWB** [comment]
@hellboy81, as i know, plugins for VS Code can be only wrote in JavaScript or TypeScript. It will be very hard to rewrite whole project to other language.

**Comment by pierre3** [comment]
Hi @hellboy81 
VS Code Extension (preview) has been released. (This is just an extension to running the .net core module.)
Please try it.

**Comment by abulka** [comment]
I installed the plugin and the latest .net core 3 on a mac, and get the following error when I run the vscode c# to plantuml command:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      2.0.5 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
      3.0.0 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The .NET Core frameworks can be found at:
  - https://aka.ms/dotnet-download
```

Do I really need to install an older, specific dotnet in order for the plugin to work?  Surely it should work with my default and latest dotnet?

**Comment by pierre3** [comment]
Added support for .NET Core 3.0 in [v1.2.0](https://www.nuget.org/packages/PlantUmlClassDiagramGenerator/1.2.0). 
Try this version.
