### ISSUE TITLE
Model Class attributes as class associations

### ISSUE THREAD

**Issue by rianwouters** [pierre3/PlantUmlClassDiagramGenerator#8]
I noticed that attributes are not modelled as class associations, which makes it very hard to see the coherence of generated classes

I'd propose an option to model attributes that have a non-simple class type to model as association,

so        
``` 
class Foo 
{
  private readonly List<Bar> bars = new List<Bar>();
}
```
would become 
```
Foo "- bars" --> "*" Bar
```

**Comment by IanIsFluent** [comment]
Does this not work with arrays?

I generated my UML, but the fact that it doesn't treat system types like `Guid` and `DateTime` as 'simple' types means I have to go in and edit the UML code. Once I've done that, my code and UML have diverged :(

If there was a [SimpleType] attribute I could put on the properties, so this extension didn't create a new UML block for them, that would be enough!

**Comment by eestein** [comment]
@pierre3 Hi! This is marked as completed, but Guids and Lists continue to be added as an association. I read the readme and could not find how to prevent that behavior. Am I missing something?
