### ISSUE TITLE
Commit branch that source generator on main

### ISSUE THREAD

**Issue by ignatandrei** [pierre3/PlantUmlClassDiagramGenerator#95]
I am maintaining a list of Roslyn Source Code Generators at

https://ignatandrei.github.io/RSCG_Examples/v2/docs/rscg-examples

And I think it will be nice to add yours .

Could you commit branch that source generator on main , to be sure that it is maintained somehow ?

**Comment by pierre3** [comment]
@ignatandrei 
I have visited the website. It's a fantastic initiative.
I would also like this repository to be included if possible. I have merged it into the master branch, so please take a look.

**Comment by ignatandrei** [comment]
Done ;-)

https://ignatandrei.github.io/RSCG_Examples/v2/docs/PlantUmlClassDiagramGenerator
